// Code generated by "stringer -type=Type -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidType-0]
	_ = x[BoolType-1]
	_ = x[StringType-2]
	_ = x[IntType-3]
	_ = x[Float64Type-4]
	_ = x[DurationType-5]
	_ = x[StringSliceType-6]
}

const _Type_name = "invalidboolstringintfloat64time.Duration[]string"

var _Type_index = [...]uint8{0, 7, 11, 17, 20, 27, 40, 48}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
