// Code generated by "stringer -type OptionType -linecomment"; DO NOT EDIT.

package cli

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[Bool-1]
	_ = x[String-2]
	_ = x[Int-3]
	_ = x[Float64-4]
	_ = x[Duration-5]
	_ = x[StringSlice-6]
}

const _OptionType_name = "invalidboolstringintfloat64time.Duration[]string"

var _OptionType_index = [...]uint8{0, 7, 11, 17, 20, 27, 40, 48}

func (i OptionType) String() string {
	if i < 0 || i >= OptionType(len(_OptionType_index)-1) {
		return "OptionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OptionType_name[_OptionType_index[i]:_OptionType_index[i+1]]
}
