// Code generated by "gen-enum -type=OutputLevel"; DO NOT EDIT.
package cli

import "errors"

func _() {
	// An "invalid array index" compiler error signifies that the constant
	// values have changed. Run the generator again.
	var x [1]struct{}
	_ = x[DebugLevel-0]
	_ = x[InfoLevel-1]
	_ = x[WarnLevel-2]
	_ = x[ErrorLevel-3]
	_ = x[FatalLevel-4]
	_ = x[PanicLevel-5]
}

var _OutputLevel_string_to_type = map[string]OutputLevel{
	"DEBUG": DebugLevel,
	"INFO":  InfoLevel,
	"WARN":  WarnLevel,
	"ERROR": ErrorLevel,
	"FATAL": FatalLevel,
	"PANIC": PanicLevel,
}

var _OutputLevel_type_to_string = map[OutputLevel]string{
	DebugLevel: "DEBUG",
	InfoLevel:  "INFO",
	WarnLevel:  "WARN",
	ErrorLevel: "ERROR",
	FatalLevel: "FATAL",
	PanicLevel: "PANIC",
}

var ErrInvalidOutputLevel = errors.New("invalid OutputLevel")

func (i OutputLevel) String() string {
	return _OutputLevel_type_to_string[i]
}

func StringToOutputLevel(s string) OutputLevel {
	if t, ok := _OutputLevel_string_to_type[s]; ok {
		return t
	}
	return 0
}

func IsOutputLevel(s string) bool {
	if _, ok := _OutputLevel_string_to_type[s]; ok {
		return true
	}
	return false
}

func OutputLevelList() []OutputLevel {
	return []OutputLevel{
		DebugLevel,
		InfoLevel,
		WarnLevel,
		ErrorLevel,
		FatalLevel,
		PanicLevel,
	}
}
