ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

# Enable all available rules.
enableAllRules = true

# Rule tuning.
[rule.add-constant]
  arguments = [{maxLitCount = "5", allowStrs = "\"\"", allowInts = "0,1", allowFloats = "0.0"}]

[rule.argument-limit]
  arguments = [4]

[rule.cognitive-complexity]
  arguments = [9]

[rule.cyclomatic]
  arguments = [8]

[rule.function-result-limit]
  arguments = [3]

[rule.var-naming]
  arguments = [[""], ["ID", "VM"]]

# Disabled rules.
[rule.banned-characters]
  disabled = true

[rule.exported]
  disabled = true

[rule.file-header]
  disabled = true

[rule.function-length]
  disabled = true

[rule.line-length-limit]
  disabled = true

[rule.max-public-structs]
  disabled = true

# Project supports Go 1.17 and up so we can't enable this yet.
[rule.use-any]
  disabled = true