ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

# Disable all available rules by default.
enableAllRules = false

# Rule tuning.
[rule.argument-limit]
  arguments = [4]

[rule.cognitive-complexity]
  arguments = [50]

[rule.cyclomatic]
  arguments = [50]

[rule.duplicated-imports]
[rule.early-return]
[rule.empty-block]
[rule.error-naming]
[rule.error-return]
[rule.error-strings]
[rule.errorf]
[rule.flag-parameter]

[rule.function-result-limit]
  arguments = [3]

[rule.get-return]
[rule.identical-branches]
[rule.if-return]
[rule.increment-decrement]
[rule.indent-error-flow]

[rule.imports-blacklist]
  arguments = ["github.com/pkg/errors"]

[rule.import-shadowing]
[rule.modifies-parameter]
[rule.modifies-value-receiver]
[rule.nested-structs]
[rule.optimize-operands-order]
[rule.range]
[rule.range-val-in-closure]
[rule.range-val-address]
[rule.receiver-naming]
[rule.redefines-builtin-id]
[rule.string-of-int]
[rule.struct-tag]
[rule.superfluous-else]
[rule.time-equal]
[rule.time-naming]

[rule.var-naming]
  arguments = [[""], ["ID", "VM"]]

[rule.var-declaration]
[rule.unconditional-recursion]
[rule.unexported-naming]
[rule.unexported-return]
[rule.unnecessary-stmt]
[rule.unreachable-code]
[rule.unused-parameter]
[rule.unused-receiver]
[rule.use-any]
[rule.useless-break]
[rule.waitgroup-by-value]
